### PR TITLE
Add Instagram insight sample

### PR DESCRIPTION
**Pull request by akito19**
Add workflow sample of Instagram Use and Media Insights import.

See: https://tddocs.atlassian.net/wiki/spaces/PD/pages/1081577/Instagram+User+and+Media+Insights+Import+Integration

### CODE REVIEW

**Comment by mickeey2525** [comment]
Is the below variable declaration is necessary?

```
shopify:
    target: products
    from_date: "${last_session_date}"
    fetch_days: 2
```

**Comment by akito19** [comment]
@mickeey2525 Oops, thank you for catching.

**Comment by mickeey2525** [comment]
Sorry for one more thing.

The doc's title does not contain Instagram. Is this intentional?
I believe `Treasure Data's Data Connector for Instagram User and Media Insights` is correct.

**Comment by akito19** [comment]
Ah, it was intentional because the README title was `Workflow: Instagram User and Media Insights`.
It was wordy for me to see "Instagram User and Media Insights" twice in first few lines.

However, I'll update that link text (and I'm fixing typo...).

**Pull request merged**
