### PR TITLE
Add fuzzy-match as a new Box

### PR DESCRIPTION
**Pull request by PrachiChavan14**

### CODE REVIEW

**Comment by toru-takahashi** [comment]
Looks some of images are located in your local.
Could you please change the image urls?

**Comment by PrachiChavan14** [comment]
> Looks some of images are located in your local.
> Could you please change the image urls?

Hi Toru , I have changed the image urls , could you please check again

**Comment by toru-takahashi** [comment]
@PrachiChavan14 Could you add more info about "Getting Started"?

It would be nice if you can add the following info.

- Where/How can a user add "First Name and Last Name table"?
- What's your expected first step to run the workflow?

**Comment by PrachiChavan14** [comment]
Hi Toru ,

I have updated the information in the Getting started section.
I am working on the code to provide database name and table name as a variable , and will update the code section soon

Regards,

**Comment by toru-takahashi** [comment]
Cool! Looks good to me!

**Pull request merged**
