### PR TITLE
Test indresh

### PR DESCRIPTION
**Pull request by indreshkumartd**

### CODE REVIEW

**Comment by toru-takahashi** [comment]
Is there any reason you want to create SFTP connector on UI?
The following can run Connecgtor job from Workflow. So that we can manage it on Workflow
https://github.com/treasure-data/treasure-boxes/tree/master/td_load/sftp

**Comment by indreshkumartd** [comment]
> Is there any reason you want to create SFTP connector on UI?
> The following can run Connecgtor job from Workflow. So that we can manage it on Workflow
> https://github.com/treasure-data/treasure-boxes/tree/master/td_load/sftp

Yes, The reason is that we need to create the sftp connector(s) for each data file available on sftp and load each file data to separate td table. So instead of creating each sftp connector for each data file manually from UI, We can use this custom python to that. 
Also, The workflow link you shared will not solve our purpose as it will only load one set of files to td table.
Please do let me know if you have still have any concerns.

**Comment by toru-takahashi** [comment]
The sample is a simple usecase. They can use variables and they can run a loop with multiple table name if you use for_each operator.
We don't need to create a connector on UI.
Connector UI doesn't support variables and back-fill. Thus, for the production usecase, we don't recommend it.

This sample is too much to do a bad practice.
I don't think this is good for others.

**Comment by indreshkumartd** [comment]
Thanks for response!!. Can we have quick call/meeting to discuss/short it out the confusion which I/you have in this? Please share the time when we can do this as per your availability.

**Comment by hadrianhu** [comment]
@indreshkumartd, this is ivan with Td support, I will ping you on slack so we can arrange a call to discuss, a call will be easier to explain the different approached.

**Comment by indreshkumartd** [comment]
Hi @toru-takahashi, 

I am closing this PR. As creating the separate connectors may not be good approach for all sftp files. So What I will be doing is that using  python code to create the guessed files dynamically for each data file available over sftp and then run the td_load command for each yml file created using existing below wf.
https://github.com/treasure-data/treasure-boxes/tree/master/td_load/sftp

cc: hadrianhu

Thanks.

**Pull request closed without merging**
